---
stages:
  - lint
  - publish

lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - ansible-lint --show-relpath .
  only:
    - main
    - merge_requests

publish:
  stage: publish
  image: registry.gitlab.com/asharas/docker-ansible:latest
  script:
    - ansible-galaxy role import --role-name steamcmd --api-key $GALAXY_API_KEY Asharas Ansible-Steamcmd
  only:
    - main
